---
# tasks file for ansible-role-npppd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'FreeBSD'

- name: Create log directory
  file:
    path: "{{ npppd_log_dir }}"
    mode: 0755
    owner: "{{ npppd_user }}"
    group: "{{ npppd_group }}"
    state: directory
  notify: Restart npppd

- name: Create db directory
  file:
    path: "{{ npppd_db_dir }}"
    mode: 0755
    owner: "{{ npppd_user }}"
    group: "{{ npppd_group }}"
    state: directory
  notify: Restart npppd

- name: Create npppd.conf
  template:
    src: npppd.conf.j2
    dest: "{{ npppd_conf }}"
  notify: Restart npppd

- name: Start npppd
  service:
    name: "{{ npppd_service }}"
    enabled: true
    state: started
