---
# tasks file for ansible-role-npppd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create conf directory
  file:
    path: "{{ npppd_conf_dir }}"
    mode: 0755
    state: directory

- name: Create npppd-users
  template:
    src: npppd-users.j2
    dest: "{{ npppd_users_file }}"
    mode: 0600

- name: Create npppd.conf
  template:
    src: npppd.conf.j2
    dest: "{{ npppd_conf }}"
  notify: Restart npppd

- name: Start npppd
  service:
    name: "{{ npppd_service }}"
    enabled: true
    state: started
